"""
Every migration ships a `downgrade()`, but nothing previously verified it
actually works — an autogenerated downgrade commonly drops tables fine
while leaving the ENUM types Postgres created for their `sa.Enum(...)`
columns behind, which then breaks the *next* upgrade with "type already
exists" instead of recreating them cleanly. That exact bug was found by
hand while adding this test (see migrations/versions/
b09900336144_initial_schema.py's downgrade — it now explicitly drops all
12 enum types after dropping the tables). This test exercises the full
downgrade-to-base-then-upgrade-to-head round trip against a live database
so a regression here fails a test instead of surfacing the next time
someone happens to roll a migration back by hand.

Like the other Postgres-only checks, this needs a live, reachable database
and skips (or fails, under RECON_REQUIRE_DATABASE_TESTS=1) without one. It
always restores the database to `head` before returning, even on failure,
since every other DB-dependent test assumes the schema is fully migrated.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from core.config import get_settings
from tests.db_gate import skip_or_fail

pytest.importorskip("sqlalchemy")
pytest.importorskip("alembic")

from alembic import command  # noqa: E402
from alembic.config import Config  # noqa: E402
from sqlalchemy import create_engine, text  # noqa: E402

_BACKEND_DIR = Path(__file__).resolve().parents[2]


def _alembic_config() -> Config:
    config = Config(str(_BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(_BACKEND_DIR / "migrations"))
    return config


def _require_live_database() -> None:
    settings = get_settings()
    try:
        engine = create_engine(settings.database_url, connect_args={"connect_timeout": 2})
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except Exception:
        skip_or_fail("no live database configured — run in the integration environment")


def test_downgrade_to_base_then_upgrade_to_head_is_clean():
    _require_live_database()
    config = _alembic_config()
    try:
        command.downgrade(config, "base")
        command.upgrade(config, "head")
    finally:
        # Whatever happened above, leave the database fully migrated —
        # every other integration test assumes `head` is applied.
        command.upgrade(config, "head")
