import { ArrowRight, ArrowUpRight, Bot, Check, CheckCheck, CircleCheck, Clock3, FileCheck2, FileText, Landmark, LoaderCircle, LockKeyhole, ShieldCheck, Sparkles, UploadCloud } from 'lucide-react';
import type { Workspace } from './types';
import { friendlyStatus, money } from './presentation';

type Props = {data:Workspace;period:string;actor:string;busy:boolean;onUpload:(side?:string)=>void;onCheck:()=>void;onReview:(id?:string)=>void;onFiles:()=>void;onHistory:()=>void;onClose:()=>void;onSample:()=>void};
export default function Dashboard({data,period,actor,busy,onUpload,onCheck,onReview,onFiles,onHistory,onClose,onSample}:Props){
  const records=data.records.filter(r=>r.period===period);
  const batches=data.imports.filter(b=>b.period===period);
  const cases=data.breaks.filter(b=>b.period===period);
  const active=cases.filter(b=>!['CLOSED','RESOLVED'].includes(b.status));
  const ready=active.filter(b=>b.status==='PROPOSED');
  const matched=records.filter(r=>r.status==='MATCHED').length;
  const resolved=records.filter(r=>r.status==='EXPLAINED').length;
  const rate=records.length?Math.round(matched/records.length*100):0;
  const sources=['SOURCE_A','SOURCE_B'].map(side=>({side,count:records.filter(r=>r.side===side).length,files:batches.filter(b=>b.side===side&&b.status==='COMMITTED').length}));
  const held=batches.filter(b=>b.status==='HELD').length;
  const missing=sources.find(s=>!s.count);
  const locked=data.periods[period]?.status==='CERTIFIED';
  const lastRun=data.runs.filter(r=>r.period===period).at(-1);
  const covered=new Set(active.flatMap(b=>b.record_ids));
  const unchecked=records.some(r=>r.status==='UNMATCHED'&&!covered.has(r.id));
  const unprepared=active.some(b=>['OPEN','TRIAGED','REJECTED','RETURNED','CARRIED_FORWARD'].includes(b.status));
  const canCheck=actor==='analyst'&&!missing&&!held&&!locked&&(unchecked||unprepared);
  let title='Next Action',description='',button='Review Differences',handler=()=>onReview();
  if(locked){title='This month is complete';description='Your sign-off and supporting records are saved. You can view the month-end summary anytime.';button='View month-end summary';handler=onClose;}
  else if(held){title=`${held} ${held===1?'file needs':'files need'} attention`;description='Open your uploads to see which rows need fixing. Your original files are kept.';button='Check uploaded files';handler=onFiles;}
  else if(missing){title=records.length?'Add the other set of records':'Start with your two source files';description=actor==='analyst'?'Upload a bank statement and the accounting records for the same account and month. The agent will compare them for you.':'An analyst needs to upload both source files before you can review the results.';button=actor==='analyst'?(missing.side==='SOURCE_A'?'Upload bank records':'Upload accounting records'):'View uploaded files';handler=actor==='analyst'?()=>onUpload(missing.side):onFiles;}
  else if(canCheck){title='Records ready for reconciliation';description='Run reconciliation to match entries and prepare recommendations for remaining differences.';button='Check Records';handler=onCheck;}
  else if(ready.length){title=`${ready.length} ${ready.length===1?'recommendation is':'recommendations are'} ready for review`;description=actor==='reviewer'?'Compare the evidence and approve the next step, or ask for more information.':actor==='analyst'?'Review the findings and supporting evidence. A reviewer must approve recommended actions.':'Open the findings to see what still needs review before month-end.';button='Review Differences';}
  else if(active.length){title=`${active.length} ${active.length===1?'difference needs':'differences need'} follow-up`;description='Open each difference to see the evidence or information needed to finish it.';}
  else if(records.length){title='The records are ready for month-end review';description='There are no open differences for this month. Open the checklist for the final human sign-off.';button='Review month-end';handler=onClose;}
  const priority=[...active].sort((a,b)=>(b.risk==='High'?1:0)-(a.risk==='High'?1:0)||a.created_at.localeCompare(b.created_at)).slice(0,3);

  return <div className="simple-dashboard">
    <section className="purpose-banner" aria-labelledby="agent-purpose"><div className="purpose-content"><span className="purpose-kicker"><Sparkles size={15}/>RECONCILIATION COPILOT</span><h2 id="agent-purpose">Automated Record Review</h2><p>Your agent matches transactions and prepares recommendations for unmatched entries.</p><span className="human-control"><ShieldCheck size={15}/>All recommended actions require human approval.</span></div><div className="comparison-illustration" aria-hidden="true"><div className="illustration-file bank"><Landmark size={22}/><strong>Bank records</strong><i/><i/><i/></div><div className="illustration-agent"><Bot size={31}/><span><Check size={11}/></span></div><div className="illustration-file ledger"><FileText size={22}/><strong>Accounting records</strong><i/><i/><i/></div><span className="illustration-caption"><CheckCheck size={14}/>Compare · explain · recommend</span></div></section>
    <div className="simple-steps" aria-label="How reconciliation works">{[{title:'Upload Records',text:'Bank + accounting records',icon:UploadCloud,done:!missing,go:onFiles},{title:'Run Reconciliation',text:'Matching + recommendations',icon:Bot,done:!!lastRun&&!unchecked&&!unprepared,go:onHistory},{title:'Review Results',text:'Human approval required',icon:FileCheck2,done:!!records.length&&!active.length,go:()=>onReview()}].map((step,i)=><button key={step.title} onClick={step.go} className={step.done?'simple-step complete':'simple-step'}><span className="step-number">{step.done?<Check size={16}/>:i+1}</span><span><strong>{step.title}</strong><small>{step.text}</small></span>{i<2&&<ArrowRight className="step-arrow" size={18}/>}</button>)}</div>
    <section className={`next-step-card ${locked?'month-done':''}`} aria-labelledby="next-step-title"><span className="next-step-icon">{busy?<LoaderCircle className="spin" size={25}/>:locked?<CircleCheck size={25}/>:<Bot size={25}/>}</span><div><span className="eyebrow">{busy?'AGENT IS WORKING':'Next Action'}</span><h2 id="next-step-title">{busy?'Checking your records and preparing recommendations…':title}</h2><p>{busy?'This can take a little time. Your results will appear here when the check finishes.':description}</p></div><button className="button primary" disabled={busy} onClick={handler}>{button}<ArrowRight size={16}/></button></section>
    <div className="simple-metrics" aria-label="This month at a glance"><div className="simple-metric"><span><CheckCheck size={18}/>Entries matched</span><strong className="stat-value">{matched.toLocaleString()}<small>of {records.length.toLocaleString()}</small></strong><p>{records.length?`${rate}% matched${resolved?` · ${resolved} explained separately`:''}`:'Results appear after your first check'}</p><div className="metric-progress"><i style={{width:`${rate}%`}}/></div></div><button className="simple-metric" onClick={()=>onReview()}><span><FileText size={18}/>Open differences</span><strong className="stat-value">{active.length}<ArrowUpRight size={20}/></strong><p>{active.some(b=>b.risk==='High')?`${active.filter(b=>b.risk==='High').length} high-priority items to look at first`:active.length?'Open a difference to see the next step':'No open differences in this month'}</p></button><button className="simple-metric" onClick={()=>onReview(ready[0]?.id)}><span><Sparkles size={18}/>Recommendations ready</span><strong className="stat-value">{ready.length}<ArrowUpRight size={20}/></strong><p>{ready.length?'Source evidence included for your review':'The agent prepares these after checking'}</p></button></div>
    <div className="dashboard-work-grid"><section className="panel priority-panel"><div className="panel-heading"><div><h2>{priority.length?'Priority Differences':'Review Summary'}</h2><p>Findings requiring review or follow-up.</p></div>{active.length>0&&<button className="text-button" onClick={()=>onReview()}>View all differences <ArrowRight size={14}/></button>}</div>{priority.length?<div className="priority-list">{priority.map(b=><button className="priority-item" key={b.id} onClick={()=>onReview(b.id)}><span className={`priority-mark ${b.risk==='High'?'urgent':''}`}><FileText size={18}/></span><span className="priority-copy"><span className="priority-title">{b.title}<span className={`badge badge-${b.status.toLowerCase()}`}>{friendlyStatus(b.status)}</span></span><span className="priority-description">{b.description||b.reference}</span><span className="priority-next">{b.status==='ACTION_PENDING'?'Next: add proof that the action was completed':b.proposal?'Next: review the agent’s recommendation':'Next: ask the agent to investigate'}</span></span><span className="priority-amount">{money(b.amount,b.currency)}<small>entry amount</small></span><ArrowUpRight size={17}/></button>)}</div>:<div className="simple-empty"><CircleCheck size={32}/><h3>{records.length&&!unchecked?'No differences to review':'Your findings will appear here'}</h3><p>{records.length&&!unchecked?'Check the month-end checklist when you are ready.':'Add both files and let the agent check them.'}</p>{data.records.length===0&&data.imports.length===0&&actor==='analyst'&&<button className="button" disabled={busy} onClick={onSample}><Sparkles size={15}/>Try sample data</button>}</div>}</section><section className="panel source-panel"><div className="panel-heading"><div><h2>Source Files</h2><p>Bank and accounting records for the selected month.</p></div></div>{sources.map((s,i)=><div className="source-file-card" key={s.side}><span className="source-file-icon">{i===0?<Landmark size={21}/>:<FileText size={21}/>}</span><div><strong>{i===0?'Bank records':'Accounting records'}</strong><small>{s.count?`${s.files} ${s.files===1?'file':'files'} · ${s.count.toLocaleString()} entries`:'No file uploaded yet'}</small></div>{s.count?<span className="source-ready"><Check size={13}/>Ready</span>:<button className="text-button" disabled={actor!=='analyst'||locked||busy} onClick={()=>onUpload(s.side)}>Upload <ArrowUpRight size={13}/></button>}</div>)}<div className="source-help"><LockKeyhole size={14}/><p>Your original records stay unchanged.</p></div><button className="source-manage" onClick={onFiles}>Manage uploaded files <ArrowRight size={14}/></button></section></div>
    <div className="dashboard-history"><span><Clock3 size={14}/>{lastRun?`Last check: ${new Date(lastRun.created_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`:'No checks run for this month yet'}</span><button className="text-button" onClick={onHistory}>View agent history <ArrowRight size={14}/></button></div>
  </div>;
}
