# Generated by Django 6.1 on 2026-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('payout', 'Payout')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one_time', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('available_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('liquidity_threshold', models.DecimalField(decimal_places=2, default=10000, help_text='Alert when projected liquidity falls below this amount.', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
