export const CURRENCIES = [
  ["USD", "US Dollar"],
  ["EUR", "Euro"],
  ["GBP", "British Pound"],
  ["PKR", "Pakistani Rupee"],
  ["INR", "Indian Rupee"],
  ["AED", "UAE Dirham"],
  ["SAR", "Saudi Riyal"],
  ["QAR", "Qatari Riyal"],
  ["KWD", "Kuwaiti Dinar"],
  ["BHD", "Bahraini Dinar"],
  ["OMR", "Omani Rial"],
  ["JPY", "Japanese Yen"],
  ["CNY", "Chinese Yuan"],
  ["HKD", "Hong Kong Dollar"],
  ["SGD", "Singapore Dollar"],
  ["MYR", "Malaysian Ringgit"],
  ["THB", "Thai Baht"],
  ["IDR", "Indonesian Rupiah"],
  ["PHP", "Philippine Peso"],
  ["VND", "Vietnamese Dong"],
  ["KRW", "South Korean Won"],
  ["BDT", "Bangladeshi Taka"],
  ["LKR", "Sri Lankan Rupee"],
  ["NPR", "Nepalese Rupee"],
  ["AFN", "Afghan Afghani"],
  ["IRR", "Iranian Rial"],
  ["IQD", "Iraqi Dinar"],
  ["TRY", "Turkish Lira"],
  ["ILS", "Israeli Shekel"],
  ["JOD", "Jordanian Dinar"],
  ["LBP", "Lebanese Pound"],
  ["EGP", "Egyptian Pound"],
  ["ZAR", "South African Rand"],
  ["NGN", "Nigerian Naira"],
  ["KES", "Kenyan Shilling"],
  ["GHS", "Ghanaian Cedi"],
  ["MAD", "Moroccan Dirham"],
  ["DZD", "Algerian Dinar"],
  ["TND", "Tunisian Dinar"],
  ["ETB", "Ethiopian Birr"],
  ["AUD", "Australian Dollar"],
  ["NZD", "New Zealand Dollar"],
  ["CAD", "Canadian Dollar"],
  ["CHF", "Swiss Franc"],
  ["SEK", "Swedish Krona"],
  ["NOK", "Norwegian Krone"],
  ["DKK", "Danish Krone"],
  ["PLN", "Polish Zloty"],
  ["CZK", "Czech Koruna"],
  ["HUF", "Hungarian Forint"],
  ["RON", "Romanian Leu"],
  ["BGN", "Bulgarian Lev"],
  ["UAH", "Ukrainian Hryvnia"],
  ["RUB", "Russian Ruble"],
  ["KZT", "Kazakhstani Tenge"],
  ["BRL", "Brazilian Real"],
  ["MXN", "Mexican Peso"],
  ["ARS", "Argentine Peso"],
  ["CLP", "Chilean Peso"],
  ["COP", "Colombian Peso"],
  ["PEN", "Peruvian Sol"],
  ["UYU", "Uruguayan Peso"],
];
