"""initial schema

§4 — every pack-neutral core table, generated from core.models against a
live Postgres 16 instance. RLS (§20) and the agent_runtime role's grants
(§13.1) are deliberately a separate migration (0002) so the "what exists"
and "who may touch it" concerns stay independently reviewable.

Revision ID: b09900336144
Revises:
Create Date: 2026-09-07 12:04:03.458603
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b09900336144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('close_calendar_id', sa.String(), nullable=True),
    sa.Column('active_packs', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_reconciliation',
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('movement', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('explained', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('unexplained', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preparer', sa.String(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_rating', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_reconciliation_tenant_id'), 'account_reconciliation', ['tenant_id'], unique=False)
    op.create_table('agent_run',
    sa.Column('autonomy_level', sa.String(), nullable=False),
    sa.Column('budget_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cases_analysed', sa.Integer(), nullable=False),
    sa.Column('cases_skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_tenant_id'), 'agent_run', ['tenant_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('hash_prev', sa.String(), nullable=True),
    sa.Column('hash_self', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_correlation_id'), 'audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_event_tenant_id'), 'audit_event', ['tenant_id'], unique=False)
    op.create_table('break_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('risk_weight', sa.Integer(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_break_type_tenant_id'), 'break_type', ['tenant_id'], unique=False)
    op.create_table('close_period',
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SOFT_CLOSE', 'HARD_CLOSE', 'CERTIFIED', 'LOCKED', name='close_period_status'), nullable=False),
    sa.Column('deadline_prep', sa.Date(), nullable=True),
    sa.Column('deadline_review', sa.Date(), nullable=True),
    sa.Column('deadline_certify', sa.Date(), nullable=True),
    sa.Column('certifier', sa.String(), nullable=True),
    sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_close_period_tenant_id'), 'close_period', ['tenant_id'], unique=False)
    op.create_table('dimension_registry',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('STRING', 'NUMBER', 'DATE', 'UUID', name='dimension_data_type'), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_isolating', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pack_id', 'key')
    )
    op.create_index(op.f('ix_dimension_registry_tenant_id'), 'dimension_registry', ['tenant_id'], unique=False)
    op.create_table('knowledge_document',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_document_tenant_id'), 'knowledge_document', ['tenant_id'], unique=False)
    op.create_table('mapping_template',
    sa.Column('source_signature', sa.String(), nullable=False),
    sa.Column('field_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_template_source_signature'), 'mapping_template', ['source_signature'], unique=False)
    op.create_index(op.f('ix_mapping_template_tenant_id'), 'mapping_template', ['tenant_id'], unique=False)
    op.create_table('retrieval_trace',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('returned_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_trace_case_id'), 'retrieval_trace', ['case_id'], unique=False)
    op.create_index(op.f('ix_retrieval_trace_tenant_id'), 'retrieval_trace', ['tenant_id'], unique=False)
    op.create_table('routing_rule',
    sa.Column('break_family', sa.String(), nullable=False),
    sa.Column('amount_band', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dimension_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_role', sa.String(), nullable=False),
    sa.Column('escalation_role', sa.String(), nullable=True),
    sa.Column('allow_auto_match', sa.Boolean(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rule_tenant_id'), 'routing_rule', ['tenant_id'], unique=False)
    op.create_table('tolerance_profile',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tolerance_profile_tenant_id'), 'tolerance_profile', ['tenant_id'], unique=False)
    op.create_table('connector',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('credentials_ref', sa.String(), nullable=True),
    sa.Column('mapping_template_id', sa.UUID(), nullable=True),
    sa.Column('read_only_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapping_template_id'], ['mapping_template.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_tenant_id'), 'connector', ['tenant_id'], unique=False)
    op.create_table('document_chunk',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_authority', sa.Enum('POLICY', 'SOP', 'GUIDANCE', 'PRECEDENT', name='source_authority'), nullable=False),
    sa.Column('embedding_model_version', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_doc_id'), 'document_chunk', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_tenant_id'), 'document_chunk', ['tenant_id'], unique=False)
    op.create_table('universe',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('side_a_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('side_b_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tolerance_profile_id', sa.UUID(), nullable=True),
    sa.Column('require_dimension', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autonomy_level', sa.Enum('A0_OBSERVE', 'A1_PROPOSE_ON_DEMAND', 'A2_PROPOSE_ON_SCHEDULE', 'A3_AUTO_MATCH', name='autonomy_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tolerance_profile_id'], ['tolerance_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universe_tenant_id'), 'universe', ['tenant_id'], unique=False)
    op.create_table('break_case',
    sa.Column('break_type_code', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'PROPOSED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'RETURNED', 'ACTION_PENDING', 'RESOLVED', 'CLOSED', 'REOPENED', 'CARRIED_FORWARD', name='break_case_status'), nullable=False),
    sa.Column('universe_id', sa.UUID(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('carry_forward_count', sa.Integer(), nullable=False),
    sa.Column('original_period', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_case_tenant_id'), 'break_case', ['tenant_id'], unique=False)
    op.create_table('canonical_record',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('SOURCE_A', 'SOURCE_B', name='record_side'), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('booking_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('direction', sa.Enum('DR', 'CR', name='direction'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('account_ref', sa.String(), nullable=False),
    sa.Column('counterparty_raw', sa.String(), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('reference_raw', sa.String(), nullable=True),
    sa.Column('reference_canonical', sa.String(), nullable=True),
    sa.Column('description_raw', sa.String(), nullable=True),
    sa.Column('description_clean', sa.String(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('INGESTED', 'NORMALIZED', 'MATCHED', 'UNMATCHED', 'QUARANTINED', name='record_status'), nullable=False),
    sa.Column('quarantine_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_record_reference_canonical'), 'canonical_record', ['reference_canonical'], unique=False)
    op.create_index(op.f('ix_canonical_record_row_fingerprint'), 'canonical_record', ['row_fingerprint'], unique=False)
    op.create_index(op.f('ix_canonical_record_run_id'), 'canonical_record', ['run_id'], unique=False)
    op.create_index(op.f('ix_canonical_record_tenant_id'), 'canonical_record', ['tenant_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('control_totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_import_batch_tenant_id'), 'import_batch', ['tenant_id'], unique=False)
    op.create_table('match_group',
    sa.Column('universe_id', sa.UUID(), nullable=False),
    sa.Column('cardinality', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('decided_by', sa.Enum('HUMAN', 'AGENT', name='decided_by'), nullable=False),
    sa.Column('decided_autonomy_level', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_group_tenant_id'), 'match_group', ['tenant_id'], unique=False)
    op.create_table('recon_run',
    sa.Column('universe_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('pack_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_run_tenant_id'), 'recon_run', ['tenant_id'], unique=False)
    op.create_table('decision',
    sa.Column('break_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('prior_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['break_id'], ['break_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_break_id'), 'decision', ['break_id'], unique=False)
    op.create_index(op.f('ix_decision_tenant_id'), 'decision', ['tenant_id'], unique=False)
    op.create_table('external_action_ref',
    sa.Column('break_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['break_id'], ['break_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_action_ref_break_id'), 'external_action_ref', ['break_id'], unique=False)
    op.create_index(op.f('ix_external_action_ref_tenant_id'), 'external_action_ref', ['tenant_id'], unique=False)
    op.create_table('journal_draft',
    sa.Column('break_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', name='journal_draft_status'), nullable=False),
    sa.Column('posted_by', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['break_id'], ['break_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_draft_break_id'), 'journal_draft', ['break_id'], unique=False)
    op.create_index(op.f('ix_journal_draft_tenant_id'), 'journal_draft', ['tenant_id'], unique=False)
    op.create_table('match_member',
    sa.Column('match_group_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_group.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['canonical_record.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_member_match_group_id'), 'match_member', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_match_member_tenant_id'), 'match_member', ['tenant_id'], unique=False)
    op.create_table('proposal',
    sa.Column('break_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('MATCH', 'SPLIT', 'JOURNAL_DRAFT', 'EXTERNAL_ACTION', 'INFO_REQUEST', 'CARRY_FORWARD', 'ESCALATE', 'SUPPRESS_RULE', 'NO_PROPOSAL', name='proposal_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACCEPTED', 'REJECTED', 'RETURNED', name='proposal_status'), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['break_id'], ['break_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_break_id'), 'proposal', ['break_id'], unique=False)
    op.create_index(op.f('ix_proposal_tenant_id'), 'proposal', ['tenant_id'], unique=False)
    op.create_table('evidence_item',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('retrieval_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_item_proposal_id'), 'evidence_item', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_evidence_item_tenant_id'), 'evidence_item', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_item_tenant_id'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_proposal_id'), table_name='evidence_item')
    op.drop_table('evidence_item')
    op.drop_index(op.f('ix_proposal_tenant_id'), table_name='proposal')
    op.drop_index(op.f('ix_proposal_break_id'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_match_member_tenant_id'), table_name='match_member')
    op.drop_index(op.f('ix_match_member_match_group_id'), table_name='match_member')
    op.drop_table('match_member')
    op.drop_index(op.f('ix_journal_draft_tenant_id'), table_name='journal_draft')
    op.drop_index(op.f('ix_journal_draft_break_id'), table_name='journal_draft')
    op.drop_table('journal_draft')
    op.drop_index(op.f('ix_external_action_ref_tenant_id'), table_name='external_action_ref')
    op.drop_index(op.f('ix_external_action_ref_break_id'), table_name='external_action_ref')
    op.drop_table('external_action_ref')
    op.drop_index(op.f('ix_decision_tenant_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_break_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_recon_run_tenant_id'), table_name='recon_run')
    op.drop_table('recon_run')
    op.drop_index(op.f('ix_match_group_tenant_id'), table_name='match_group')
    op.drop_table('match_group')
    op.drop_index(op.f('ix_import_batch_tenant_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_canonical_record_tenant_id'), table_name='canonical_record')
    op.drop_index(op.f('ix_canonical_record_run_id'), table_name='canonical_record')
    op.drop_index(op.f('ix_canonical_record_row_fingerprint'), table_name='canonical_record')
    op.drop_index(op.f('ix_canonical_record_reference_canonical'), table_name='canonical_record')
    op.drop_table('canonical_record')
    op.drop_index(op.f('ix_break_case_tenant_id'), table_name='break_case')
    op.drop_table('break_case')
    op.drop_index(op.f('ix_universe_tenant_id'), table_name='universe')
    op.drop_table('universe')
    op.drop_index(op.f('ix_document_chunk_tenant_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_doc_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    op.drop_index(op.f('ix_connector_tenant_id'), table_name='connector')
    op.drop_table('connector')
    op.drop_index(op.f('ix_tolerance_profile_tenant_id'), table_name='tolerance_profile')
    op.drop_table('tolerance_profile')
    op.drop_index(op.f('ix_routing_rule_tenant_id'), table_name='routing_rule')
    op.drop_table('routing_rule')
    op.drop_index(op.f('ix_retrieval_trace_tenant_id'), table_name='retrieval_trace')
    op.drop_index(op.f('ix_retrieval_trace_case_id'), table_name='retrieval_trace')
    op.drop_table('retrieval_trace')
    op.drop_index(op.f('ix_mapping_template_tenant_id'), table_name='mapping_template')
    op.drop_index(op.f('ix_mapping_template_source_signature'), table_name='mapping_template')
    op.drop_table('mapping_template')
    op.drop_index(op.f('ix_knowledge_document_tenant_id'), table_name='knowledge_document')
    op.drop_table('knowledge_document')
    op.drop_index(op.f('ix_dimension_registry_tenant_id'), table_name='dimension_registry')
    op.drop_table('dimension_registry')
    op.drop_index(op.f('ix_close_period_tenant_id'), table_name='close_period')
    op.drop_table('close_period')
    op.drop_index(op.f('ix_break_type_tenant_id'), table_name='break_type')
    op.drop_table('break_type')
    op.drop_index(op.f('ix_audit_event_tenant_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_correlation_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_agent_run_tenant_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_index(op.f('ix_account_reconciliation_tenant_id'), table_name='account_reconciliation')
    op.drop_table('account_reconciliation')
    op.drop_table('tenant')
    # ### end Alembic commands ###

    # Alembic's autogenerate drops the tables above but — a known
    # SQLAlchemy/Postgres gap — never drops the ENUM types it created for
    # their `sa.Enum(...)` columns. Left in place, a later `upgrade` on the
    # same database fails with "type already exists" instead of recreating
    # them. Verified against a live database: without this block,
    # downgrade-then-upgrade leaves 12 orphaned types and the re-upgrade
    # errors on the first CREATE TYPE.
    for enum_name in (
        "close_period_status", "dimension_data_type", "source_authority",
        "autonomy_level", "break_case_status", "record_side", "direction",
        "record_status", "decided_by", "journal_draft_status",
        "proposal_kind", "proposal_status",
    ):
        op.execute(f'DROP TYPE IF EXISTS "{enum_name}"')
