# Generated by Django 6.1 on 2026-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('cash', 'Cash'), ('savings', 'Savings Account'), ('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('etfs', 'ETFs'), ('fixed_deposit', 'Fixed Deposit'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('other', 'Other Investments')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('liquidity_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('expected_return', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
