"""phase1 initial schema

Revision ID: 66b55a081037
Revises: 
Create Date: 2026-09-11 15:53:24.465870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b55a081037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TENANT_SCOPED_TABLES = (
    "users", "engagements", "datasets", "dataset_rows", "sampling_policies",
    "rule_packs", "risk_runs", "risk_scores", "sample_items", "evaluations",
    "overrides", "benchmarks", "audit_events", "audit_anchors",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('head_sequence', sa.BigInteger(), nullable=True),
    sa.Column('head_hash', sa.String(length=64), nullable=True),
    sa.Column('anchored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_audit_events_tenant_sequence')
    )
    op.create_index('ix_audit_events_tenant_subject', 'audit_events', ['tenant_id', 'subject'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_residency_region', sa.Text(), server_default='default', nullable=False),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('llm_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('viewer','auditor','reviewer','admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('performance_materiality', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.Text(), nullable=False),
    sa.Column('pack_version', sa.Text(), nullable=False),
    sa.Column('yaml_source', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pack_id', 'pack_version', name='uq_rule_pack_tenant_id_version')
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('file_sha256', sa.Text(), nullable=False),
    sa.Column('dataset_fingerprint', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('item_id_col', sa.Text(), nullable=True),
    sa.Column('amount_col', sa.Text(), nullable=True),
    sa.Column('timestamp_col', sa.Text(), nullable=True),
    sa.Column('entity_col', sa.Text(), nullable=True),
    sa.Column('schema_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'file_sha256', name='uq_datasets_tenant_sha256')
    )
    op.create_table('sampling_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('tolerable_misstatement', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expected_misstatement', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('min_sample_size', sa.Integer(), nullable=True),
    sa.Column('max_sample_size', sa.Integer(), nullable=True),
    sa.Column('high_risk_threshold', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('high_risk_top_n', sa.Integer(), nullable=True),
    sa.Column('random_control_size', sa.Integer(), nullable=True),
    sa.Column('test_negative_balances_100pct', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('review_zero_balances', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'engagement_id', 'policy_version', name='uq_policy_tenant_engagement_version')
    )
    op.create_table('dataset_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dataset_id', 'item_id', name='uq_dataset_rows_tenant_dataset_item')
    )
    op.create_index('ix_dataset_rows_tenant_dataset_item', 'dataset_rows', ['tenant_id', 'dataset_id', 'item_id'], unique=False)
    op.create_table('risk_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('user_seed', sa.Text(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('dataset_fingerprint', sa.Text(), nullable=False),
    sa.Column('risk_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomaly_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rules_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status in ('queued','running','complete','failed','cancelled')", name='ck_risk_runs_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['sampling_policies.id'], ),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('label_source', sa.Text(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['risk_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workpaper', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('signed_off_by', sa.UUID(), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['risk_runs.id'], ),
    sa.ForeignKeyConstraint(['signed_off_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_event_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(reason) >= 10', name='ck_overrides_reason_min_length'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['risk_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rule_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rules_fired', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomaly_attribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['risk_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'run_id', 'item_id', name='uq_risk_scores_tenant_run_item')
    )
    op.create_index('ix_risk_scores_tenant_run_score', 'risk_scores', ['tenant_id', 'run_id', 'risk_score'], unique=False)
    op.create_table('sample_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('stratum', sa.Text(), nullable=False),
    sa.Column('selection_basis', sa.Text(), nullable=False),
    sa.Column('projectable', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('inclusion_probability', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('audit_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tested_by', sa.UUID(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tester_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['risk_runs.id'], ),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'run_id', 'item_id', name='uq_sample_items_tenant_run_item')
    )
    # ### end Alembic commands ###

    # --- Row-level security: enforced at the database, never relying on the
    # application to remember to filter by tenant. FORCE RLS applies the
    # policy even to the table owner, so a bug in application code cannot
    # bypass isolation by accident.
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = current_setting('app.tenant_id')::uuid)"
        )

    # --- Audit trail append-only enforcement: the application role may
    # INSERT and SELECT but never UPDATE or DELETE audit_events, so a bug
    # (or a compromised app credential) cannot rewrite history. Default
    # privileges granted all four; explicitly narrow this one table.
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM app_role")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("GRANT UPDATE, DELETE ON audit_events TO app_role")

    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_items')
    op.drop_index('ix_risk_scores_tenant_run_score', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('overrides')
    op.drop_table('evaluations')
    op.drop_table('benchmarks')
    op.drop_table('risk_runs')
    op.drop_index('ix_dataset_rows_tenant_dataset_item', table_name='dataset_rows')
    op.drop_table('dataset_rows')
    op.drop_table('sampling_policies')
    op.drop_table('datasets')
    op.drop_table('rule_packs')
    op.drop_table('engagements')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index('ix_audit_events_tenant_subject', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('audit_anchors')
    # ### end Alembic commands ###
