"""phase2 auth: refresh tokens, override approval fields

Revision ID: b0c842c67f26
Revises: 66b55a081037
Create Date: 2026-09-11 16:03:42.919568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c842c67f26'
down_revision: Union[str, Sequence[str], None] = '66b55a081037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_tenant_user', 'refresh_tokens', ['tenant_id', 'user_id'], unique=False)
    op.add_column('overrides', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('overrides', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_overrides_approved_by_users', 'overrides', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###

    op.execute("ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE refresh_tokens FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON refresh_tokens "
        "USING (tenant_id = current_setting('app.tenant_id')::uuid)"
    )

    # Login must look up a user by email before the caller's tenant_id is
    # known -- RLS on `users` would otherwise block the lookup entirely.
    # A narrowly-scoped SECURITY DEFINER function (owned by the migration
    # role, which owns the table and therefore bypasses RLS internally)
    # exposes exactly the columns login needs, nothing else, instead of
    # granting app_role a blanket RLS bypass.
    op.execute(
        """
        CREATE FUNCTION login_lookup(p_email citext)
        RETURNS TABLE (
            id uuid, tenant_id uuid, password_hash text, role text, is_active boolean
        )
        LANGUAGE sql
        SECURITY DEFINER
        SET search_path = public
        AS $$
            SELECT id, tenant_id, password_hash, role, is_active
            FROM users
            WHERE email = p_email
        $$;
        """
    )
    op.execute("GRANT EXECUTE ON FUNCTION login_lookup(citext) TO app_role")

    # Same problem for refresh: the client presents an opaque token whose
    # tenant isn't known yet. This function reveals only the tenant_id for
    # a given token hash (never the token itself, since only its hash is
    # stored) so the caller can then open a properly tenant-scoped session
    # to do the actual rotation under RLS.
    op.execute(
        """
        CREATE FUNCTION refresh_token_tenant_lookup(p_token_hash text)
        RETURNS uuid
        LANGUAGE sql
        SECURITY DEFINER
        SET search_path = public
        AS $$
            SELECT tenant_id FROM refresh_tokens WHERE token_hash = p_token_hash
        $$;
        """
    )
    op.execute("GRANT EXECUTE ON FUNCTION refresh_token_tenant_lookup(text) TO app_role")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS refresh_token_tenant_lookup(text)")
    op.execute("DROP FUNCTION IF EXISTS login_lookup(citext)")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON refresh_tokens")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_overrides_approved_by_users', 'overrides', type_='foreignkey')
    op.drop_column('overrides', 'approved_at')
    op.drop_column('overrides', 'approved_by')
    op.drop_index('ix_refresh_tokens_tenant_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
