"""Generate a local Ed25519 dev keypair for testing only.

DO NOT use this script or its output for staging/production. Production
signing keys must be issued and stored by the trusted signing service /
HSM / KMS, never generated by or stored inside the Disclosure Generator.
"""
from __future__ import annotations

import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

PROJECT_ROOT = Path(__file__).resolve().parent.parent
KEYS_DIR = PROJECT_ROOT / "keys"


def main() -> None:
    KEYS_DIR.mkdir(exist_ok=True)
    private_path = KEYS_DIR / "dev_private_key.pem"
    public_path = KEYS_DIR / "dev_public_key.pem"

    if private_path.exists() or public_path.exists():
        print(f"Refusing to overwrite existing keys in {KEYS_DIR}. Delete them first if you want new ones.")
        sys.exit(1)

    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()

    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    private_path.write_bytes(private_pem)
    public_path.write_bytes(public_pem)

    print(f"Wrote dev private key: {private_path}")
    print(f"Wrote dev public key:  {public_path}")
    print("These are LOCAL DEVELOPMENT keys only. Never commit or use in production.")


if __name__ == "__main__":
    main()
